package interfacejava.veloToulouse;

import javax.swing.JOptionPane;

import veloToulouse.VeloStation;
import veloToulouse.service.VeloStationService;

/**
 *
 * @author Raphaël
 */
@SuppressWarnings("serial")
public class VeloStationFrame extends javax.swing.JFrame {

    /**
     * Creates new form VeloStationFrame
     */
    public VeloStationFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        metroUPSRadioButton = new javax.swing.JRadioButton();
        rangueilRadioButton = new javax.swing.JRadioButton();
        metroPharmaRadioButton = new javax.swing.JRadioButton();
        tripodeBRadioButton = new javax.swing.JRadioButton();
        sendRequestVeloButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        buttonGroup1.add(metroUPSRadioButton);
        metroUPSRadioButton.setText("Station Metro UPS : 227");
        metroUPSRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                metroUPSRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(rangueilRadioButton);
        rangueilRadioButton.setText("Station Rangueil : 231");
        rangueilRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rangueilRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(metroPharmaRadioButton);
        metroPharmaRadioButton.setText("Station Metro Pharmacie : 228");
        metroPharmaRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                metroPharmaRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(tripodeBRadioButton);
        tripodeBRadioButton.setText("Station TripodeB : 230");
        tripodeBRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tripodeBRadioButtonActionPerformed(evt);
            }
        });

        sendRequestVeloButton.setText("Ok !");
        sendRequestVeloButton.setEnabled(false);
        sendRequestVeloButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendRequestVeloButtonActionPerformed(evt);
            }
        });

        jTextPane1.setEditable(false);
        jTextPane1.setText("Choisissez une station veloToulouse.");
        jScrollPane2.setViewportView(jTextPane1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tripodeBRadioButton)
                            .addComponent(metroUPSRadioButton)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(metroPharmaRadioButton)
                                .addComponent(rangueilRadioButton, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(sendRequestVeloButton))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(metroUPSRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rangueilRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(metroPharmaRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tripodeBRadioButton)
                .addGap(41, 41, 41)
                .addComponent(sendRequestVeloButton)
                .addGap(0, 50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    private void tripodeBRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {
        setOKEnabled(true);
    }

    private void metroUPSRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {
        setOKEnabled(true);
    }

    private void rangueilRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {
        setOKEnabled(true);
    }

    private void metroPharmaRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {
        setOKEnabled(true);
    }

    private void sendRequestVeloButtonActionPerformed(java.awt.event.ActionEvent evt) {
        //Recuperer le radioButton choisi.
        Integer res = -2;
        int id = 0;
        VeloStationService vs = new VeloStationService();
         //executer la requete velo pour mettre à jour res
        if(metroUPSRadioButton.isSelected()) {
            id = 227;
        	//res = (Integer) vs.veloDisponibleById(227);
        }
        if(rangueilRadioButton.isSelected()) {
            id = 231;
        	//res = (Integer) vs.veloDisponibleById(231);
        }
        if(metroPharmaRadioButton.isSelected()) {
            id = 228;
        	//res = (Integer) vs.veloDisponibleById(228);
        }
        if(tripodeBRadioButton.isSelected()) {
            id = 230;
        	//res = (Integer) vs.veloDisponibleById(230);
        }
        VeloStation v = vs.getVeloStationById(id);
        res = v.getAvailableBike();
        //ouvrir fenetre selon reponse
        //JOptionPane d = new JOptionPane();
        if(res==-2)
        	JOptionPane.showMessageDialog( this, "Une erreur est survenue durant le traitement de la requète.", "Erreur traitement requète", JOptionPane.ERROR_MESSAGE);
        if(res==-1)
            JOptionPane.showMessageDialog( this, "Erreur : Station fermée", "Station Fermée", JOptionPane.ERROR_MESSAGE);
        else if(res>=0) {
            JOptionPane.showMessageDialog( this, "Il y a "+res+" vélo(s) disponible(s) et "+v.getAvailableBikeStands()+" point(s) d'attache disponible(s) sur cette station.", "Vélos disponibles", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    
    private void setOKEnabled(boolean b) {
        sendRequestVeloButton.setEnabled(b);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VeloStationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VeloStationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VeloStationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VeloStationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new VeloStationFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JRadioButton metroPharmaRadioButton;
    private javax.swing.JRadioButton metroUPSRadioButton;
    private javax.swing.JRadioButton rangueilRadioButton;
    private javax.swing.JButton sendRequestVeloButton;
    private javax.swing.JRadioButton tripodeBRadioButton;
    // End of variables declaration
}