/**
 * 
 */
package interfacejava.estimationTrajet;

import javax.swing.JOptionPane;

import veloToulouse.service.EstimationTrajetVeloService;

/**
*
* @author Raphaël
*/
@SuppressWarnings("serial")
public class EstimationTrajetFrame extends javax.swing.JFrame {

   /**
    * Creates new form EstimationtrajetFrame
    */
   public EstimationTrajetFrame() {
       initComponents();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   
   // <editor-fold defaultstate="collapsed" desc="Generated Code">
   private void initComponents() {

       jScrollPane1 = new javax.swing.JScrollPane();
       jTextPane1 = new javax.swing.JTextPane();
       adresseTextField = new javax.swing.JTextField();
       jScrollPane2 = new javax.swing.JScrollPane();
       jTextPane2 = new javax.swing.JTextPane();
       veloButton = new javax.swing.JButton();
       transportsButton = new javax.swing.JButton();

       setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

       jTextPane1.setEditable(false);
       jTextPane1.setText("Entrez une adresse sur Toulouse.");
       jScrollPane1.setViewportView(jTextPane1);

       adresseTextField.setText("Toulouse ");

       jTextPane2.setEditable(false);
       jTextPane2.setText("Choisissez un mode de transport.");
       jScrollPane2.setViewportView(jTextPane2);

       veloButton.setText("Velo TOULOUSE");
       veloButton.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               veloButtonActionPerformed(evt);
           }
       });

       transportsButton.setText("Bus/Metro");
       transportsButton.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               transportsButtonActionPerformed(evt);
           }
       });

       javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
       getContentPane().setLayout(layout);
       layout.setHorizontalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
               .addContainerGap()
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                   .addComponent(adresseTextField, javax.swing.GroupLayout.Alignment.LEADING)
                   .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                   .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                       .addComponent(veloButton)
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 190, Short.MAX_VALUE)
                       .addComponent(transportsButton))
                   .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING))
               .addContainerGap())
       );
       layout.setVerticalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addContainerGap()
               .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addComponent(adresseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGap(18, 18, 18)
               .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGap(18, 18, 18)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addComponent(transportsButton)
                   .addComponent(veloButton))
               .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
       );

       pack();
   }// </editor-fold>

   private void veloButtonActionPerformed(java.awt.event.ActionEvent evt) {
	   EstimationTrajetVeloService etvs = new EstimationTrajetVeloService();
       String adresse = adresseTextField.getText();
       //TODO appel fonctions nécessaires au calcul du temps de trajet.
       String res = etvs.calculDureeTrajet(adresse);
       //Affichage JoptionPane reponse.
       JOptionPane.showMessageDialog( this, "La durée de trajet à vélo estimé depuis l'UPS pour "+adresse+" est de "+res+" !", "Estimation trajet à vélo.", JOptionPane.INFORMATION_MESSAGE);
   }

   private void transportsButtonActionPerformed(java.awt.event.ActionEvent evt) {
	   //String adresse = adresseTextField.getText();
	   //TODO appel fonctions nécessaires au calcul du temps de trajet.
	   //Affichage JoptionPane reponse.
	   JOptionPane.showMessageDialog( this, "Erreur : Cette fonctionnalité n'est pas encore disponible.", "Estimation trajet en bus/métro.", JOptionPane.ERROR_MESSAGE);
   }

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
       /*
        * Set the Nimbus look and feel
        */
       //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
       /*
        * If Nimbus (introduced in Java SE 6) is not available, stay with the
        * default look and feel. For details see
        * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
       try {
           for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
               if ("Nimbus".equals(info.getName())) {
                   javax.swing.UIManager.setLookAndFeel(info.getClassName());
                   break;
               }
           }
       } catch (ClassNotFoundException ex) {
           java.util.logging.Logger.getLogger(EstimationTrajetFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (InstantiationException ex) {
           java.util.logging.Logger.getLogger(EstimationTrajetFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (IllegalAccessException ex) {
           java.util.logging.Logger.getLogger(EstimationTrajetFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (javax.swing.UnsupportedLookAndFeelException ex) {
           java.util.logging.Logger.getLogger(EstimationTrajetFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       }
       //</editor-fold>

       /*
        * Create and display the form
        */
       java.awt.EventQueue.invokeLater(new Runnable() {

           public void run() {
               new EstimationTrajetFrame().setVisible(true);
           }
       });
   }
   // Variables declaration - do not modify
   private javax.swing.JTextField adresseTextField;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JScrollPane jScrollPane2;
   private javax.swing.JTextPane jTextPane1;
   private javax.swing.JTextPane jTextPane2;
   private javax.swing.JButton transportsButton;
   private javax.swing.JButton veloButton;
   // End of variables declaration
}
